import {test,before,after} from 'node:test';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,deleteDoc,updateDoc,collection,collectionGroup,getDocs,query,where,runTransaction,serverTimestamp} from 'firebase/firestore';
const room='a'.repeat(48),day='2026-09-07',eventId='11111111-1111-4111-8111-111111111111';let env,owner,a,b;
const memberName='Lê Phạm Quỳnh Anh',memberNormal=memberName.normalize('NFC').toLocaleLowerCase('vi-VN');
const memberHash=createHash('sha256').update(memberNormal).digest('hex');
const ref=(db,mssv)=>doc(db,'rooms',room,'days',day,'attendance',mssv);
const payload=(uid,mssv,id)=>({uid,mssv,requestId:id,source:'camera',scannerName:'Nguyễn Văn A',scannedAt:'2026-09-07T09:00:00Z',createdAt:serverTimestamp()});
before(async()=>{
 env=await initializeTestEnvironment({projectId:'demo-attendance',firestore:{host:'127.0.0.1',port:8088,rules:await readFile(new URL('../firestore.rules',import.meta.url),'utf8')}});
 owner=env.authenticatedContext('teacher',{firebase:{sign_in_provider:'google.com'}}).firestore();
 a=env.authenticatedContext('scannerA',{firebase:{sign_in_provider:'anonymous'}}).firestore();
 b=env.authenticatedContext('scannerB',{firebase:{sign_in_provider:'anonymous'}}).firestore();
 await setDoc(doc(owner,'rooms',room),{ownerUid:'teacher',createdAt:serverTimestamp()});
});
after(async()=>{await env?.cleanup()});
test('two scanners commit same MSSV concurrently: exactly one immutable record',async()=>{
 const scan=(db,uid,id)=>runTransaction(db,async tx=>{
  const r=ref(db,'00123'),snap=await tx.get(r);if(snap.exists())return 'duplicate';
  tx.set(r,payload(uid,'00123',id));return 'saved';
 });
 const results=await Promise.all([scan(a,'scannerA','a'.repeat(36)),scan(b,'scannerB','b'.repeat(36))]);
 assert.deepEqual(results.sort(),['duplicate','saved']);
 const original=(await getDoc(ref(a,'00123'))).data();assert(['scannerA','scannerB'].includes(original.uid));
 await assertFails(setDoc(ref(b,'00123'),payload('scannerB','00123','c'.repeat(36))));
 assert.equal((await getDoc(ref(a,'00123'))).data().requestId,original.requestId);
});
test('unauthenticated user cannot read, write, or enumerate',async()=>{
 const guest=env.unauthenticatedContext().firestore();
 await assertFails(getDoc(ref(guest,'00123')));await assertFails(getDoc(doc(guest,'rooms',room)));
 await assertFails(setDoc(ref(guest,'234'),payload('guest','234','a'.repeat(36))));
});
test('participants cannot download the class list; only its owner can enumerate it',async()=>{
 await assertFails(getDocs(collection(b,'rooms',room,'days',day,'attendance')));
 await assertSucceeds(getDocs(collection(owner,'rooms',room,'days',day,'attendance')));
 await assertFails(getDocs(collection(b,'rooms')));await assertFails(deleteDoc(ref(b,'00123')));
 await assertSucceeds(getDocs(query(collection(owner,'rooms'),where('ownerUid','==','teacher'))));
});
test('rules validate identity, code, timestamp, and extra fields',async()=>{
 await assertFails(setDoc(ref(a,'bad1'),payload('scannerB','bad1','a'.repeat(36))));
 await assertFails(setDoc(ref(a,'bad2'),payload('scannerA','different','a'.repeat(36))));
 await assertFails(setDoc(ref(a,'bad3'),{...payload('scannerA','bad3','a'.repeat(36)),admin:true}));
 await assertFails(setDoc(ref(a,'bad4'),{...payload('scannerA','bad4','a'.repeat(36)),createdAt:new Date(0)}));
 await assertFails(setDoc(ref(a,'bad5'),{...payload('scannerA','bad5','a'.repeat(36)),scannerName:''}));
 await assertFails(setDoc(ref(a,'bad6'),{...payload('scannerA','bad6','a'.repeat(36)),scannerName:'x'.repeat(81)}));
 await assertSucceeds(setDoc(ref(a,'00234'),payload('scannerA','00234','a'.repeat(36))));
 await assertSucceeds(deleteDoc(ref(owner,'00234')));
});
test('anonymous users cannot create rooms or change room ownership',async()=>{
 await assertFails(setDoc(doc(a,'rooms','b'.repeat(48)),{ownerUid:'scannerA',createdAt:serverTimestamp()}));
 await assertFails(setDoc(doc(owner,'rooms',room),{ownerUid:'scannerA',createdAt:serverTimestamp()}));
});
test('only owner can name a day; participants can read the name',async()=>{
 const dayRef=doc(owner,'rooms',room,'days',day);
 await assertSucceeds(setDoc(dayRef,{eventName:'Điểm danh Đồ án Nội thất 4',updatedAt:serverTimestamp()}));
 assert.equal((await getDoc(doc(a,'rooms',room,'days',day))).data().eventName,'Điểm danh Đồ án Nội thất 4');
 await assertFails(setDoc(doc(a,'rooms',room,'days',day),{eventName:'Đổi trái phép',updatedAt:serverTimestamp()}));
 await assertFails(setDoc(dayRef,{eventName:'',updatedAt:serverTimestamp()}));
 await assertFails(setDoc(dayRef,{eventName:'x'.repeat(101),updatedAt:serverTimestamp()}));
});
test('owner can publish the default scanner room; anonymous users can only read it',async()=>{
 const eventRef=doc(owner,'rooms',room,'days',day,'events',eventId);
 await assertSucceeds(setDoc(eventRef,{eventName:'Ca sáng',day,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));
 const ownerDefault=doc(owner,'public','default');
 await assertSucceeds(setDoc(ownerDefault,{room,day,eventId,updatedAt:serverTimestamp()}));
 assert.equal((await getDoc(doc(a,'public','default'))).data().room,room);
 await assertFails(setDoc(doc(a,'public','default'),{room,day,eventId,updatedAt:serverTimestamp()}));
 await assertFails(setDoc(ownerDefault,{room:'b'.repeat(48),day,eventId,updatedAt:serverTimestamp()}));
});

test('event link permits scanning while the member list grants delegated management',async()=>{
 const eventRef=doc(owner,'rooms',room,'days',day,'events',eventId),memberRef=doc(owner,'rooms',room,'days',day,'events',eventId,'members',memberHash);
 await assertSucceeds(setDoc(memberRef,{name:memberName,normalized:memberNormal,createdAt:serverTimestamp()}));
 await assertSucceeds(updateDoc(memberRef,{name:'LÊ PHẠM QUỲNH ANH',normalized:memberNormal}));
 await assertFails(updateDoc(doc(a,'rooms',room,'days',day,'events',eventId,'members',memberHash),{name:'Tên giả'}));
 await assertSucceeds(updateDoc(memberRef,{name:memberName,normalized:memberNormal}));
 assert.equal((await getDoc(doc(a,'rooms',room,'days',day,'events',eventId,'members',memberHash))).data().name,memberName);
 await assertFails(getDocs(collection(a,'rooms',room,'days',day,'events',eventId,'members')));
 await assertSucceeds(getDocs(collection(owner,'rooms',room,'days',day,'events',eventId,'members')));
 await assertFails(getDocs(collection(a,'rooms',room,'days',day,'events',eventId,'attendance')));
 const scan=(uid,mssv,hash=memberHash,name=memberName)=>({mssv,scannedAt:'2026-09-07T10:00:00Z',source:'camera',memberName:name,memberHash:hash,eventId,eventName:'Ca sáng',requestId:'d'.repeat(36),uid,createdAt:serverTimestamp()});
 const ordinary=doc(b,'rooms',room,'days',day,'events',eventId,'attendance','12000001');
 await assertSucceeds(setDoc(ordinary,scan('scannerB','12000001','f'.repeat(64),'Người quét thường')));
 await assertFails(deleteDoc(ordinary));
 const accessA=doc(a,'rooms',room,'days',day,'events',eventId,'access','scannerA');
 await assertFails(setDoc(doc(b,'rooms',room,'days',day,'events',eventId,'access','scannerB'),{uid:'scannerB',memberHash:'f'.repeat(64),memberName:'Người lạ',grantedAt:serverTimestamp()}));
 await assertSucceeds(setDoc(accessA,{uid:'scannerA',memberHash,memberName,grantedAt:serverTimestamp()}));
 await assertSucceeds(getDocs(collection(a,'rooms',room,'days',day,'events',eventId,'attendance')));
 await assertFails(getDocs(collection(b,'rooms',room,'days',day,'events',eventId,'attendance')));
 await assertSucceeds(deleteDoc(doc(a,'rooms',room,'days',day,'events',eventId,'attendance','12000001')));
 const attendance=doc(a,'rooms',room,'days',day,'events',eventId,'attendance','12300325');
 await assertSucceeds(setDoc(attendance,scan('scannerA','12300325')));
 await assertFails(setDoc(doc(a,'rooms',room,'days',day,'events',eventId,'attendance','12300326'),scan('scannerA','12300326','f'.repeat(64),'')));
 await assertSucceeds(deleteDoc(attendance));
 await assertFails(deleteDoc(doc(a,'rooms',room,'days',day,'events',eventId)));
 await assertFails(deleteDoc(doc(a,'rooms',room,'days',day,'events',eventId,'members',memberHash)));
 const event2='22222222-2222-4222-8222-222222222222';
 await assertSucceeds(setDoc(doc(owner,'rooms',room,'days',day,'events',event2),{eventName:'Ca chiều',day,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));
 await assertSucceeds(setDoc(doc(a,'rooms',room,'days',day,'events',event2,'attendance','12300325'),{...scan('scannerA','12300325'),eventId:event2,eventName:'Ca chiều'}));
 await assertFails(getDocs(collection(a,'rooms',room,'days',day,'events',event2,'attendance')));
 await assertSucceeds(getDocs(collection(owner,'rooms',room,'days',day,'events',event2,'attendance')));
 await assertSucceeds(setDoc(doc(owner,'publicEvents',eventId),{room,day,eventId,updatedAt:serverTimestamp()}));
 assert.equal((await getDoc(doc(b,'publicEvents',eventId))).data().eventId,eventId);
});

test('event photo is visible only to its uploader and owner',async()=>{
 const id='33333333-3333-4333-8333-333333333333',imageData='data:image/jpeg;base64,'+'A'.repeat(120);
 const photo=db=>doc(db,'rooms',room,'days',day,'events',eventId,'unread',id);
 await assertSucceeds(setDoc(photo(a),{imageData,takenAt:'2026-09-07T10:05:00Z',memberName,memberHash,eventId,eventName:'Ca sáng',uid:'scannerA',createdAt:serverTimestamp()}));
 await assertSucceeds(getDoc(photo(a)));await assertFails(getDoc(photo(b)));
 await assertSucceeds(getDocs(collection(a,'rooms',room,'days',day,'events',eventId,'unread')));
 await assertFails(getDocs(collection(b,'rooms',room,'days',day,'events',eventId,'unread')));
 await assertSucceeds(getDocs(collection(owner,'rooms',room,'days',day,'events',eventId,'unread')));
 await assertSucceeds(updateDoc(photo(a),{mssv:'12300325'}));
 await assertFails(updateDoc(photo(b),{mssv:'12300326'}));
 await assertFails(updateDoc(photo(a),{mssv:'SAI'}));
 await assertFails(updateDoc(photo(a),{imageData:'data:image/jpeg;base64,'+'B'.repeat(120)}));
 await assertSucceeds(updateDoc(photo(owner),{mssv:'12300326'}));
 const idB='44444444-4444-4444-8444-444444444444',photoB=db=>doc(db,'rooms',room,'days',day,'events',eventId,'unread',idB);
 await assertSucceeds(setDoc(photoB(b),{imageData,takenAt:'2026-09-07T10:06:00Z',memberName:'Người quét thường',memberHash:'f'.repeat(64),eventId,eventName:'Ca sáng',uid:'scannerB',createdAt:serverTimestamp()}));
 const ownQuery=query(collection(b,'rooms',room,'days',day,'events',eventId,'unread'),where('uid','==','scannerB'));
 assert.equal((await assertSucceeds(getDocs(ownQuery))).size,1);
 await assertFails(deleteDoc(photo(a)));
 await assertSucceeds(deleteDoc(photo(owner)));
 await assertSucceeds(deleteDoc(photoB(owner)));
 const accessRef=doc(a,'rooms',room,'days',day,'events',eventId,'access','scannerA');
 await assertFails(deleteDoc(doc(b,'rooms',room,'days',day,'events',eventId,'access','scannerA')));
 await assertSucceeds(deleteDoc(accessRef));
});
test('scanner can upload and view their own photo; only owner can list or delete it',async()=>{
 const id='12345678-1234-1234-1234-123456789abc';
 const photoRef=db=>doc(db,'rooms',room,'days',day,'unread',id);
 const imageData='data:image/jpeg;base64,'+'A'.repeat(120);
 await assertSucceeds(setDoc(photoRef(a),{imageData,scannerName:'Người quét A',takenAt:'2026-09-07T09:10:00Z',uid:'scannerA',createdAt:serverTimestamp()}));
 assert.equal((await assertSucceeds(getDoc(photoRef(a)))).data().uid,'scannerA');
 await assertFails(getDoc(photoRef(b)));
 await assertFails(getDocs(collection(a,'rooms',room,'days',day,'unread')));
 assert.equal((await getDoc(photoRef(owner))).data().scannerName,'Người quét A');
 await assertSucceeds(getDocs(collection(owner,'rooms',room,'days',day,'unread')));
 await assertFails(setDoc(doc(a,'rooms',room,'days',day,'unread','22345678-1234-1234-1234-123456789abc'),{imageData:'not-an-image',scannerName:'A',takenAt:'2026-09-07T09:10:00Z',uid:'scannerA',createdAt:serverTimestamp()}));
 await assertSucceeds(deleteDoc(photoRef(owner)));
});
test('owner manages admins; admin operates events but only deletes own events',async()=>{
 const email='admin@example.com',admin=env.authenticatedContext('adminUid',{email,firebase:{sign_in_provider:'google.com'}}).firestore();
 const adminRef=doc(owner,'rooms',room,'admins',email);
 await assertSucceeds(setDoc(adminRef,{email,name:'Quản trị viên',addedByUid:'teacher',addedAt:serverTimestamp()}));
 const found=await assertSucceeds(getDocs(query(collectionGroup(admin,'admins'),where('email','==',email))));assert.equal(found.size,1);
 await assertFails(setDoc(doc(admin,'rooms',room,'admins','other@example.com'),{email:'other@example.com',name:'Khác',addedByUid:'adminUid',addedAt:serverTimestamp()}));
 await assertFails(deleteDoc(doc(admin,'rooms',room,'admins',email)));
 const ownEvent='55555555-5555-4555-8555-555555555555',ownerEvent='66666666-6666-4666-8666-666666666666';
 const ownRef=doc(admin,'rooms',room,'days',day,'events',ownEvent),ownerRef=doc(owner,'rooms',room,'days',day,'events',ownerEvent);
 await assertSucceeds(setDoc(ownRef,{eventName:'Sự kiện admin',day,createdByUid:'adminUid',createdByEmail:email,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));
 await assertSucceeds(setDoc(ownerRef,{eventName:'Sự kiện GV',day,createdByUid:'teacher',createdByEmail:'teacher@example.com',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));
 await assertSucceeds(updateDoc(ownRef,{eventName:'Admin cập nhật',updatedAt:serverTimestamp()}));
 await assertSucceeds(setDoc(doc(admin,'publicEvents',ownEvent),{room,day,eventId:ownEvent,updatedAt:serverTimestamp()}));
 await assertSucceeds(getDocs(query(collection(admin,'publicEvents'),where('room','==',room))));
 await assertFails(deleteDoc(doc(admin,'rooms',room,'days',day,'events',ownerEvent)));
 await assertSucceeds(deleteDoc(ownRef));
 await assertSucceeds(deleteDoc(doc(admin,'publicEvents',ownEvent)));
 await assertSucceeds(deleteDoc(ownerRef));
 await assertSucceeds(deleteDoc(adminRef));
});
