import {test,before,after} from 'node:test';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,deleteDoc,updateDoc,collection,collectionGroup,getDocs,query,where,writeBatch,serverTimestamp,Timestamp,runTransaction} from 'firebase/firestore';

const room='a'.repeat(48),day='2026-09-09';let env,owner,subA,subB,senior,manager,scanner;
const contexts={owner:['teacher','teacher@example.com'],subA:['subA','a@example.com'],subB:['subB','b@example.com'],senior:['senior','senior@example.com'],manager:['manager','manager@example.com']};
const auth=(uid,email)=>env.authenticatedContext(uid,{email,firebase:{sign_in_provider:'google.com'}}).firestore();
const life=()=>({status:'open',closedByUid:'',closedByLevel:'',closedAt:null,endDay:'2026-09-11',endAt:Timestamp.fromMillis(Date.now()+2*86400000),reopenUntil:Timestamp.fromMillis(Date.now()+9*86400000)});
const eventData=(uid,email,name)=>({eventName:name,day,createdByUid:uid,createdByEmail:email,createdByName:name,...life(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
async function addAdmin(email,name,role='sub',can=false){const data={email,name,role,canManageSubAdmins:can,addedByUid:'teacher',addedAt:serverTimestamp()};const batch=writeBatch(owner);batch.set(doc(owner,'rooms',room,'admins',email),data);batch.set(doc(owner,'adminAccess',email),{...data,room});await assertSucceeds(batch.commit());}
async function createEvent(db,id,uid,email,name){const batch=writeBatch(db);batch.set(doc(db,'rooms',room,'days',day,'events',id),eventData(uid,email,name));batch.set(doc(db,'publicEvents',id),{room,day,eventId:id,createdByUid:uid,updatedAt:serverTimestamp()});await assertSucceeds(batch.commit());}

before(async()=>{env=await initializeTestEnvironment({projectId:'demo-attendance',firestore:{host:'127.0.0.1',port:8088,rules:await readFile(new URL('../firestore.rules',import.meta.url),'utf8')}});owner=auth(...contexts.owner);await setDoc(doc(owner,'rooms',room),{ownerUid:'teacher',createdAt:serverTimestamp()});await addAdmin('a@example.com','Sub A');await addAdmin('b@example.com','Sub B');await addAdmin('senior@example.com','Admin cao','senior',false);await addAdmin('manager@example.com','Admin cao quyền cấp','senior',true);subA=auth(...contexts.subA);subB=auth(...contexts.subB);senior=auth(...contexts.senior);manager=auth(...contexts.manager);scanner=env.authenticatedContext('scan1',{firebase:{sign_in_provider:'anonymous'}}).firestore();});
after(async()=>env?.cleanup());

test('Sub Admin chỉ liệt kê và xóa sự kiện do chính mình tạo',async()=>{await createEvent(subA,'1111111111','subA','a@example.com','Sự kiện A');await createEvent(subB,'2222222222','subB','b@example.com','Sự kiện B');const own=query(collection(subA,'rooms',room,'days',day,'events'),where('createdByUid','==','subA'));assert.equal((await assertSucceeds(getDocs(own))).size,1);await assertFails(getDocs(collection(subA,'rooms',room,'days',day,'events')));await assertFails(deleteDoc(doc(subA,'rooms',room,'days',day,'events','2222222222')));await assertSucceeds(deleteDoc(doc(subA,'rooms',room,'days',day,'events','1111111111')));});

test('Admin cấp cao xem và xóa mọi sự kiện',async()=>{assert.equal((await assertSucceeds(getDocs(collection(senior,'rooms',room,'days',day,'events')))).size,1);await createEvent(subA,'3333333333','subA','a@example.com','Sự kiện mới');await assertSucceeds(deleteDoc(doc(senior,'rooms',room,'days',day,'events','3333333333')));});

test('chỉ Admin cấp cao có dấu cấp quyền mới thêm/xóa được Sub Admin',async()=>{const email='new@example.com',data={email,name:'New',role:'sub',canManageSubAdmins:false,addedByUid:'manager',addedAt:serverTimestamp()};await assertFails(setDoc(doc(senior,'rooms',room,'admins',email),{...data,addedByUid:'senior'}));const batch=writeBatch(manager);batch.set(doc(manager,'rooms',room,'admins',email),data);batch.set(doc(manager,'adminAccess',email),{...data,room});await assertSucceeds(batch.commit());await assertFails(setDoc(doc(manager,'rooms',room,'admins','x@example.com'),{email:'x@example.com',name:'X',role:'senior',canManageSubAdmins:false,addedByUid:'manager',addedAt:serverTimestamp()}));await assertSucceeds(deleteDoc(doc(manager,'rooms',room,'admins',email)));});

test('Sub Admin không mở lại sự kiện do Admin cấp cao kết thúc',async()=>{const ref=doc(subB,'rooms',room,'days',day,'events','2222222222');await assertSucceeds(updateDoc(ref,{status:'closed',closedByUid:'subB',closedByLevel:'sub',closedAt:serverTimestamp(),updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(ref,{status:'open',closedByUid:'',closedByLevel:'',closedAt:null,updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(senior,'rooms',room,'days',day,'events','2222222222'),{status:'closed',closedByUid:'senior',closedByLevel:'senior',closedAt:serverTimestamp(),updatedAt:serverTimestamp()}));await assertFails(updateDoc(ref,{status:'open',closedByUid:'',closedByLevel:'',closedAt:null,updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(senior,'rooms',room,'days',day,'events','2222222222'),{status:'open',closedByUid:'',closedByLevel:'',closedAt:null,updatedAt:serverTimestamp()}));});

test('danh sách đăng ký chỉ staff sự kiện được tải lên',async()=>{const roster=doc(subB,'rooms',room,'days',day,'events','2222222222','roster','12300325');await assertSucceeds(setDoc(roster,{mssv:'12300325',name:'Nguyễn Văn A',uploadedAt:serverTimestamp()}));await assertFails(setDoc(doc(scanner,'rooms',room,'days',day,'events','2222222222','roster','12300326'),{mssv:'12300326',name:'Nguyễn Văn B',uploadedAt:serverTimestamp()}));});

test('chỉ Chủ sở hữu và Admin cấp cao quản lý danh sách sinh viên dùng chung',async()=>{const mssv='12300325',email='12300325@student.tdtu.edu.vn',common={mssv,name:'Nguyễn Văn A',updatedByUid:'teacher',updatedAt:serverTimestamp()};const batch=writeBatch(owner);batch.set(doc(owner,'rooms',room,'students',mssv),common);batch.set(doc(owner,'studentAccess',email),{email,room,...common});await assertSucceeds(batch.commit());await assertFails(setDoc(doc(subA,'rooms',room,'students','12300326'),{mssv:'12300326',name:'Nguyễn Văn B',updatedByUid:'subA',updatedAt:serverTimestamp()}));assert.equal((await assertSucceeds(getDoc(doc(scanner,'rooms',room,'students',mssv)))).data().name,'Nguyễn Văn A');await assertFails(getDocs(collection(scanner,'rooms',room,'students')));});

test('ảnh nhập MSSV tạo lượt điểm danh có tên sinh viên và liên kết ảnh',async()=>{const id='44444444-4444-4444-8444-444444444444',eventId='2222222222',memberName='Người quét',memberHash=createHash('sha256').update('nguoi quet').digest('hex'),photo=doc(scanner,'rooms',room,'days',day,'events',eventId,'unread',id),scan=doc(scanner,'rooms',room,'days',day,'events',eventId,'attendance','12300325'),student=doc(scanner,'rooms',room,'students','12300325'),imageData='data:image/jpeg;base64,'+'A'.repeat(120);await assertSucceeds(setDoc(photo,{imageData,takenAt:new Date().toISOString(),memberName,memberHash,eventId,eventName:'Sự kiện B',uid:'scan1',createdAt:serverTimestamp()}));const result=await assertSucceeds(runTransaction(scanner,async tx=>{const [p,st]=await Promise.all([tx.get(photo),tx.get(student)]),takenAt=p.data().takenAt;tx.update(photo,{mssv:'12300325'});tx.set(scan,{mssv:'12300325',studentName:st.data().name,room,day,scannedAt:takenAt,source:'photo',photoId:id,memberName,memberHash,eventId,eventName:'Sự kiện B',requestId:id,uid:'scan1',createdAt:serverTimestamp()});}));assert.ok(result===undefined);assert.equal((await getDoc(scan)).data().studentName,'Nguyễn Văn A');});

test('sinh viên TDTU chỉ tra cứu được lịch sử của chính mình',async()=>{const studentDb=env.authenticatedContext('student123',{email:'12300325@student.tdtu.edu.vn',email_verified:true,firebase:{sign_in_provider:'google.com'}}).firestore(),otherDb=env.authenticatedContext('student999',{email:'99999999@student.tdtu.edu.vn',email_verified:true,firebase:{sign_in_provider:'google.com'}}).firestore();assert.equal((await assertSucceeds(getDoc(doc(studentDb,'studentAccess','12300325@student.tdtu.edu.vn')))).data().mssv,'12300325');const own=query(collectionGroup(studentDb,'attendance'),where('mssv','==','12300325'));assert.equal((await assertSucceeds(getDocs(own))).size,1);await assertFails(getDocs(query(collectionGroup(studentDb,'attendance'),where('mssv','==','12300326'))));await assertFails(getDoc(doc(otherDb,'studentAccess','12300325@student.tdtu.edu.vn')));});
