import {FirebaseAttendance} from '../firebase-sync.mjs?v=1.2.1-ui1';
import {vietnamDay} from '../sync-core.mjs';
import {DEFAULT_FIREBASE_CONFIG} from '../firebase-config.mjs';
const $=id=>document.getElementById(id),cloud=new FirebaseAttendance({scannerUrl:'../',change:render});window.attendanceCloud=cloud;
let editingDetails=false,viewerScale=1,calendarMonth=new Date(vietnamDay()+'T00:00:00');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=v=>{try{return new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'medium'}).format(v?.toDate?v.toDate():new Date(v));}catch{return v||'';}};
const safe=v=>String(v||'diem_danh').replace(/[<>:"/\\|?*\u0000-\u001F]/g,' ').replace(/\s+/g,' ').trim().slice(0,80)||'diem_danh';
const isoDay=(y,m,d)=>`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;

function renderCalendar(){
  const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();
  $('calendarLabel').textContent=new Intl.DateTimeFormat('vi-VN',{month:'long',year:'numeric'}).format(calendarMonth);
  const cells=[];for(let i=0;i<first;i++)cells.push('<span></span>');for(let d=1;d<=last;d++){const day=isoDay(y,m,d),selected=day===cloud.day,marked=cloud.eventDays?.has(day);cells.push(`<button type="button" class="calendar-day${selected?' selected':''}" data-calendar-day="${day}"><span>${d}</span>${marked?'<i title="Có sự kiện"></i>':''}</button>`);}$('calendarDays').innerHTML=cells.join('');
}
function render(){
  const manager=cloud.manager(),googleSignedIn=!!cloud.auth?.currentUser?.providerData?.some(p=>p.providerId==='google.com');$('adminStatus').className='status'+(cloud.message.includes('không')||cloud.message.includes('Chưa')?' error':'');$('adminStatus').textContent=cloud.message;
  $('loginBtn').hidden=manager;$('loginBtn').parentElement.hidden=manager;$('logoutBtn').hidden=!googleSignedIn;$('manager').hidden=!manager;$('ownerAdminPanel').hidden=!cloud.owner;
  const compactSync=manager&&/^Đã đồng bộ:/.test(cloud.message);$('accessCard').hidden=compactSync;if(!manager)return;
  $('roleLabel').textContent=cloud.owner?'Chủ sở hữu':'Admin';$('day').value=cloud.day;renderCalendar();
  const options=['<option value="">'+(cloud.events.length?'Chọn sự kiện':'Chưa có sự kiện')+'</option>',...cloud.events.map(e=>`<option value="${esc(e.id)}">${esc(e.eventName)}</option>`)].join('');if($('eventSelect').innerHTML!==options)$('eventSelect').innerHTML=options;$('eventSelect').value=cloud.eventId||'';
  if(!editingDetails){$('eventName').value=cloud.eventName||'';$('members').value=(cloud.members||[]).map(m=>m.name).join('\n');}
  const creator=cloud.currentEvent?.createdByName||cloud.currentEvent?.createdByEmail||'';$('eventCreator').textContent=cloud.eventId?'Người tạo: '+(creator||'Không ghi nhận'):'';
  const selected=!!cloud.eventId,sync=$('syncStatus');sync.hidden=!selected;sync.textContent=cloud.serverReady?'✓ Đã đồng bộ':'Đang đồng bộ…';sync.className='sync-badge'+(cloud.serverReady?'':' loading');for(const id of ['saveEventBtn','copyLinkBtn','excelBtn','csvBtn','jsonBtn','deleteAllBtn'])$(id).disabled=!selected;$('deleteEventBtn').disabled=!cloud.canDeleteCurrentEvent();$('shareLink').value=selected?cloud.shareLink():'';
  const archive=cloud.allEvents||[];$('eventArchiveEmpty').hidden=!!archive.length;$('eventArchiveRows').innerHTML=archive.map((event,i)=>`<tr><td>${i+1}</td><td><b>${esc(event.eventName||'Sự kiện')}</b></td><td>${esc(event.day)}</td><td>${esc(event.createdByName||event.createdByEmail||'Không ghi nhận')}</td><td>${esc(time(event.createdAt))}</td><td><button class="primary" data-open-event="${esc(event.id)}" data-event-day="${esc(event.day)}">Mở</button></td></tr>`).join('');
  $('adminRows').innerHTML=(cloud.admins||[]).map(a=>`<tr><td>${esc(a.name||'—')}</td><td>${esc(a.email)}</td><td><button class="danger" data-remove-admin="${esc(a.email)}">Xóa quyền</button></td></tr>`).join('');$('adminEmpty').hidden=!!cloud.admins?.length;
  const rows=cloud.rows||[];$('savedCount').textContent=rows.length+' lượt';$('empty').hidden=!!rows.length;$('rows').innerHTML=[...rows].reverse().map((r,i)=>`<tr><td class="stt-col">${rows.length-i}</td><td class="mssv-col"><b>${esc(r.mssv)}</b></td><td class="member-col">${esc(r.memberName||'Không rõ')}</td><td class="delete-col"><button class="danger" data-delete-scan="${esc(r.mssv)}">Xóa</button></td><td class="time-col">${esc(time(r.time))}</td><td class="event-col">${esc(r.eventName||cloud.eventName)}</td></tr>`).join('');
  const photos=cloud.photos||[];$('photoCount').textContent=photos.length+' ảnh';$('photoEmpty').hidden=!!photos.length;$('photoRows').innerHTML=[...photos].reverse().map((p,i)=>`<tr><td>${photos.length-i}</td><td>${p.mssv?`<b>${esc(p.mssv)}</b><br>`:''}<button class="photo-link" data-view-photo="${esc(p.id)}">Xem hình</button></td><td>${esc(p.memberName||'Không rõ')}</td><td>${esc(time(p.takenAt))}</td><td><input class="inline-input" data-photo-input="${esc(p.id)}" maxlength="12" placeholder="Nhập MSSV" value="${esc(p.mssv||'')}"></td><td><button class="primary" data-photo-save="${esc(p.id)}">Lưu MSSV</button> <button class="danger" data-photo-delete="${esc(p.id)}">Xóa</button></td></tr>`).join('');
}
function action(fn){return async()=>{try{await fn();editingDetails=false;render();}catch(e){cloud.error(e);$('adminStatus').className='status error';$('adminStatus').textContent=cloud.message;}};}
$('loginBtn').onclick=action(()=>cloud.login());$('logoutBtn').onclick=action(()=>cloud.logout());$('day').onchange=()=>{editingDetails=false;calendarMonth=new Date($('day').value+'T00:00:00');cloud.setDay($('day').value);};
$('toggleCalendarBtn').onclick=()=>{const calendar=$('eventCalendar'),opening=calendar.hidden;calendar.hidden=!opening;$('toggleCalendarBtn').textContent=opening?'Ẩn lịch':'📅 Lịch sự kiện';if(opening)renderCalendar();};
$('showAllEventsBtn').onclick=()=>{$('eventArchiveDialog').showModal();};$('closeEventArchive').onclick=()=>$('eventArchiveDialog').close();$('eventArchiveRows').onclick=async e=>{const button=e.target.closest('[data-open-event]');if(!button)return;$('eventArchiveDialog').close();calendarMonth=new Date(button.dataset.eventDay+'T00:00:00');$('day').value=button.dataset.eventDay;editingDetails=false;await action(()=>cloud.loadEvent(button.dataset.eventDay,button.dataset.openEvent))();};
$('prevMonth').onclick=()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()-1,1);renderCalendar();};$('nextMonth').onclick=()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1);renderCalendar();};$('calendarDays').onclick=e=>{const b=e.target.closest('[data-calendar-day]');if(!b)return;$('day').value=b.dataset.calendarDay;editingDetails=false;cloud.setDay(b.dataset.calendarDay);};
$('eventSelect').onchange=action(async()=>{editingDetails=false;if($('eventSelect').value)await cloud.selectEvent($('eventSelect').value);});$('eventName').oninput=$('members').oninput=()=>{editingDetails=true;};$('newEventBtn').onclick=()=>{$('newEventName').value='';$('newMembers').value='';$('newEventDialog').showModal();};$('cancelNewEvent').onclick=()=>$('newEventDialog').close();$('createEventBtn').onclick=action(async()=>{await cloud.createEvent($('newEventName').value,$('newMembers').value);$('newEventDialog').close();});
$('saveEventBtn').onclick=action(()=>cloud.saveEventDetails($('eventName').value,$('members').value));$('copyLinkBtn').onclick=action(async()=>{await navigator.clipboard.writeText(cloud.shareLink());cloud.message='Đã sao chép link riêng của sự kiện.';});$('deleteEventBtn').onclick=async()=>{if(confirm('Xóa sự kiện này cùng toàn bộ dữ liệu? Thao tác không thể hoàn tác.'))await action(()=>cloud.deleteCurrentEvent())();};
$('addAdminBtn').onclick=action(async()=>{await cloud.addAdmin($('adminEmail').value,$('adminName').value);$('adminEmail').value='';$('adminName').value='';});$('adminRows').onclick=async e=>{const b=e.target.closest('[data-remove-admin]');if(b&&confirm('Xóa quyền admin của '+b.dataset.removeAdmin+'?'))await action(()=>cloud.removeAdmin(b.dataset.removeAdmin))();};
$('rows').onclick=async e=>{const b=e.target.closest('[data-delete-scan]');if(b&&confirm('Xóa lượt quét MSSV '+b.dataset.deleteScan+'?'))await action(()=>cloud.deleteAttendance(b.dataset.deleteScan))();};$('photoRows').onclick=async e=>{const view=e.target.closest('[data-view-photo]'),save=e.target.closest('[data-photo-save]'),remove=e.target.closest('[data-photo-delete]');if(view){const p=cloud.photos.find(x=>x.id===view.dataset.viewPhoto);if(p)viewImage(p.imageData);}if(save){const id=save.dataset.photoSave,input=document.querySelector(`[data-photo-input="${id}"]`);await action(()=>cloud.resolvePhoto(id,input.value))();}if(remove&&confirm('Xóa hình chụp này?'))await action(()=>cloud.deletePhoto(remove.dataset.photoDelete))();};
function viewImage(src){viewerScale=1;$('viewerImage').src=src;applyZoom();$('imageViewerDialog').showModal();}function applyZoom(){viewerScale=Math.max(.5,Math.min(4,viewerScale));$('viewerImage').style.width=(viewerScale*100)+'%';$('zoomReset').textContent=Math.round(viewerScale*100)+'%';}$('closeImageViewer').onclick=()=>$('imageViewerDialog').close();$('zoomIn').onclick=()=>{viewerScale+=.25;applyZoom();};$('zoomOut').onclick=()=>{viewerScale-=.25;applyZoom();};$('zoomReset').onclick=()=>{viewerScale=1;applyZoom();};
function exportRows(){const byMssv=new Map((cloud.rows||[]).map(r=>[r.mssv,{...r}]));for(const p of cloud.photos||[])if(p.mssv&&!byMssv.has(p.mssv))byMssv.set(p.mssv,{...p,time:p.takenAt});return [...byMssv.values()].sort((a,b)=>a.mssv.localeCompare(b.mssv,undefined,{numeric:true})).map((r,i)=>({STT:i+1,MSSV:r.mssv,'Sự kiện':r.eventName||cloud.eventName,'Thành viên quét':r.memberName||'Không rõ','Thời gian':time(r.time)}));}
function filename(ext){return safe(cloud.eventName)+'_'+cloud.day+'.'+ext;}$('excelBtn').onclick=()=>{const ws=XLSX.utils.json_to_sheet(exportRows()),wb=XLSX.utils.book_new();ws['!cols']=[{wch:7},{wch:18},{wch:35},{wch:30},{wch:22}];XLSX.utils.book_append_sheet(wb,ws,'Diem danh');XLSX.writeFile(wb,filename('xlsx'));};$('csvBtn').onclick=()=>{const blob=new Blob(['\ufeff'+XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(exportRows()))],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename('csv');a.click();URL.revokeObjectURL(a.href);};$('jsonBtn').onclick=()=>{const blob=new Blob([JSON.stringify({day:cloud.day,eventId:cloud.eventId,eventName:cloud.eventName,members:cloud.members,attendance:cloud.rows,photos:cloud.photos},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename('json');a.click();URL.revokeObjectURL(a.href);};$('deleteAllBtn').onclick=async()=>{if(confirm('Xóa toàn bộ lượt điểm danh của sự kiện đang chọn? Hãy xuất Excel trước.'))await action(()=>cloud.clearVisible())();};
$('day').value=vietnamDay();await cloud.prepare(DEFAULT_FIREBASE_CONFIG);if(cloud.settings)await cloud.restore();render();
