import {FirebaseAttendance} from '../firebase-sync.mjs?v=1.3';
import {vietnamDay} from '../sync-core.mjs';
import {DEFAULT_FIREBASE_CONFIG} from '../firebase-config.mjs';

const $=id=>document.getElementById(id),cloud=new FirebaseAttendance({scannerUrl:'../',change:render});window.attendanceCloud=cloud;
let editing=false,viewerScale=1,calendarMonth=new Date(vietnamDay()+'T00:00:00');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=v=>{try{return new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'medium'}).format(v?.toDate?v.toDate():new Date(v));}catch{return v||'';}};
const safe=v=>String(v||'diem_danh').replace(/[<>:"/\\|?*\u0000-\u001F]/g,' ').replace(/\s+/g,' ').trim().slice(0,80)||'diem_danh';
const isoDay=(y,m,d)=>`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
const plusDays=(day,n)=>{const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return isoDay(d.getFullYear(),d.getMonth(),d.getDate());};
const eventLabel=e=>`${e.eventName||'Sự kiện'} – ${e.createdByName||e.createdByEmail||'Không ghi nhận'}`;

function renderCalendar(){const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();$('calendarLabel').textContent=new Intl.DateTimeFormat('vi-VN',{month:'long',year:'numeric'}).format(calendarMonth);const cells=[];for(let i=0;i<first;i++)cells.push('<span></span>');for(let d=1;d<=last;d++){const day=isoDay(y,m,d);cells.push(`<button type="button" class="calendar-day${day===cloud.day?' selected':''}" data-calendar-day="${day}"><span>${d}</span>${cloud.eventDays?.has(day)?'<i title="Có sự kiện"></i>':''}</button>`);}$('calendarDays').innerHTML=cells.join('');}

function roleText(a){return a.role==='senior'?'Admin cấp cao'+(a.canManageSubAdmins?' • được cấp Sub Admin':''):'Sub Admin';}
function renderRoster(){
  const c=cloud.rosterComparison(),has=cloud.roster.length>0;$('rosterPresent').textContent=c.present.length;$('rosterAbsent').textContent=c.absent.length;$('rosterOutside').textContent=c.outside.length;$('rosterEmpty').hidden=has||c.outside.length>0;
  const attended=new Set(cloud.rows.map(r=>r.mssv)),registered=new Set(cloud.roster.map(r=>r.mssv)),rows=[...cloud.roster.map(r=>({...r,state:attended.has(r.mssv)?'Có mặt':'Vắng'})),...c.outside.map(r=>({mssv:r.mssv,name:'—',state:'Không có tên trong danh sách'}))];
  $('rosterRows').innerHTML=rows.map(r=>`<tr><td><b>${esc(r.mssv)}</b></td><td>${esc(r.name)}</td><td class="${r.state==='Có mặt'?'state-open':r.state==='Vắng'?'state-closed':''}">${esc(r.state)}</td></tr>`).join('');
}
function render(){
  const manager=cloud.manager(),google=!!cloud.auth?.currentUser?.providerData?.some(p=>p.providerId==='google.com');$('adminStatus').className='status'+(/không|Chưa|từ chối/i.test(cloud.message)?' error':'');$('adminStatus').textContent=cloud.message;$('loginBtn').hidden=manager;$('loginBtn').parentElement.hidden=manager;$('logoutBtn').hidden=!google;$('manager').hidden=!manager;$('ownerAdminPanel').hidden=!cloud.mayManageAdmins();$('accessCard').hidden=manager&&/^Đã đồng bộ:/.test(cloud.message);if(!manager)return;
  $('roleLabel').textContent=cloud.owner?'Chủ sở hữu':cloud.isSenior()?'Admin cấp cao':'Sub Admin';$('day').value=cloud.day;renderCalendar();
  $('adminRoleWrap').hidden=!cloud.owner;$('manageSubsWrap').hidden=!cloud.owner||$('adminRole').value!=='senior';
  const options=['<option value="">'+(cloud.events.length?'Chọn sự kiện':'Chưa có sự kiện')+'</option>',...cloud.events.map(e=>`<option value="${esc(e.id)}">${esc(eventLabel(e))}</option>`)].join('');if($('eventSelect').innerHTML!==options)$('eventSelect').innerHTML=options;$('eventSelect').value=cloud.eventId||'';
  if(!editing){$('eventName').value=cloud.eventName||'';$('members').value=(cloud.members||[]).map(m=>m.name).join('\n');}
  const selected=!!cloud.eventId,canEdit=selected&&cloud.canOperateEvent(),creator=cloud.currentEvent?.createdByName||cloud.currentEvent?.createdByEmail||'';$('eventCreator').textContent=selected?'Người tạo: '+(creator||'Không ghi nhận'):'';
  const sync=$('syncStatus');sync.hidden=!selected;sync.textContent=cloud.serverReady?'✓ Đã đồng bộ':'Đang đồng bộ…';sync.className='sync-badge'+(cloud.serverReady?'':' loading');
  for(const id of ['copyLinkBtn','excelBtn','csvBtn','jsonBtn'])$(id).disabled=!selected;$('saveEventBtn').disabled=!canEdit;$('rosterFile').disabled=!canEdit;$('deleteEventBtn').disabled=!cloud.canDeleteCurrentEvent();$('deleteAllBtn').disabled=!selected||!cloud.isSenior();$('shareLink').value=selected?cloud.shareLink():'';
  const open=cloud.isEventOpen();$('eventState').textContent=selected?`Trạng thái: ${open?'Đang mở':'Đã kết thúc'}${cloud.currentEvent?.endDay?' • Ngày kết thúc: '+cloud.currentEvent.endDay:''}`:'';$('eventState').className='note '+(open?'state-open':'state-closed');$('closeEventBtn').disabled=!canEdit;$('closeEventBtn').textContent=open?'Kết thúc sự kiện ngay':'Mở lại sự kiện';
  const archive=cloud.allEvents||[];$('eventArchiveEmpty').hidden=!!archive.length;$('eventArchiveRows').innerHTML=archive.map((e,i)=>`<tr><td>${i+1}</td><td><b>${esc(eventLabel(e))}</b></td><td>${esc(e.day)}</td><td>${esc(e.createdByName||e.createdByEmail||'Không ghi nhận')}</td><td>${esc(time(e.createdAt))}</td><td><button class="primary" data-open-event="${esc(e.id)}" data-event-day="${esc(e.day)}">Mở</button></td></tr>`).join('');
  $('adminRows').innerHTML=(cloud.admins||[]).map(a=>`<tr><td>${esc(a.name||'—')}</td><td>${esc(a.email)}</td><td>${esc(roleText(a))}</td><td><button class="danger" data-remove-admin="${esc(a.email)}">Xóa quyền</button></td></tr>`).join('');$('adminEmpty').hidden=!!cloud.admins?.length;
  const photosById=new Map(cloud.photos.map(p=>[p.id,p])),rows=cloud.rows||[];$('savedCount').textContent=rows.length+' lượt';$('empty').hidden=!!rows.length;$('rows').innerHTML=[...rows].reverse().map((r,i)=>{const image=r.photoId&&photosById.has(r.photoId)?`<button class="photo-link" data-view-photo="${esc(r.photoId)}" title="Xem hình"><b>${esc(r.mssv)}</b> 🖼️</button>`:`<b>${esc(r.mssv)}</b>`;return `<tr><td class="stt-col">${rows.length-i}</td><td class="mssv-col">${image}</td><td class="member-col">${esc(r.memberName||'Không rõ')}</td><td class="delete-col"><button class="danger" data-delete-scan="${esc(r.mssv)}">Xóa</button></td><td class="time-col">${esc(time(r.time))}</td><td class="event-col">${esc(r.eventName||cloud.eventName)}</td></tr>`;}).join('');
  const pending=cloud.photos.filter(p=>!p.mssv);$('photoCount').textContent=pending.length+' ảnh';$('photoEmpty').hidden=!!pending.length;$('photoRows').innerHTML=[...pending].reverse().map((p,i)=>`<tr><td>${pending.length-i}</td><td><button class="photo-link" data-view-photo="${esc(p.id)}">Xem hình</button></td><td>${esc(p.memberName||'Không rõ')}</td><td>${esc(time(p.takenAt))}</td><td><input class="inline-input" data-photo-input="${esc(p.id)}" maxlength="12" placeholder="Nhập MSSV"></td><td><button class="primary" data-photo-save="${esc(p.id)}">Lưu MSSV</button> <button class="danger" data-photo-delete="${esc(p.id)}">Xóa</button></td></tr>`).join('');renderRoster();
}
function action(fn){return async()=>{try{await fn();editing=false;render();}catch(e){cloud.error(e);$('adminStatus').className='status error';$('adminStatus').textContent=cloud.message;}};}

$('loginBtn').onclick=action(()=>cloud.login());$('logoutBtn').onclick=action(()=>cloud.logout());$('day').onchange=()=>{editing=false;calendarMonth=new Date($('day').value+'T00:00:00');cloud.setDay($('day').value);};
$('toggleCalendarBtn').onclick=()=>{const c=$('eventCalendar'),open=c.hidden;c.hidden=!open;$('toggleCalendarBtn').textContent=open?'Ẩn lịch':'📅 Lịch sự kiện';if(open)renderCalendar();};$('showAllEventsBtn').onclick=()=>$('eventArchiveDialog').showModal();$('closeEventArchive').onclick=()=>$('eventArchiveDialog').close();
$('eventArchiveRows').onclick=async e=>{const b=e.target.closest('[data-open-event]');if(!b)return;$('eventArchiveDialog').close();calendarMonth=new Date(b.dataset.eventDay+'T00:00:00');$('day').value=b.dataset.eventDay;editing=false;await action(()=>cloud.loadEvent(b.dataset.eventDay,b.dataset.openEvent))();};
$('prevMonth').onclick=()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()-1,1);renderCalendar();};$('nextMonth').onclick=()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1);renderCalendar();};$('calendarDays').onclick=e=>{const b=e.target.closest('[data-calendar-day]');if(b){$('day').value=b.dataset.calendarDay;editing=false;cloud.setDay(b.dataset.calendarDay);}};
$('eventSelect').onchange=action(async()=>{editing=false;if($('eventSelect').value)await cloud.selectEvent($('eventSelect').value);});$('eventName').oninput=$('members').oninput=()=>{editing=true;};
$('newEventBtn').onclick=()=>{$('newEventName').value='';$('newMembers').value='';$('newEndDay').value=plusDays(vietnamDay(),2);$('newEndDay').min=vietnamDay();$('newEndDay').max=plusDays(vietnamDay(),10);$('newEventDialog').showModal();};$('cancelNewEvent').onclick=()=>$('newEventDialog').close();$('createEventBtn').onclick=action(async()=>{await cloud.createEvent($('newEventName').value,$('newMembers').value,$('newEndDay').value);$('newEventDialog').close();});
$('saveEventBtn').onclick=action(()=>cloud.saveEventDetails($('eventName').value,$('members').value));$('copyLinkBtn').onclick=action(async()=>{await navigator.clipboard.writeText(cloud.shareLink());cloud.message='Đã sao chép link riêng của sự kiện.';});$('closeEventBtn').onclick=async()=>{const closing=cloud.isEventOpen();if(confirm(closing?'Kết thúc sự kiện ngay? Thành viên sẽ không thể quét thêm.':'Mở lại sự kiện này?'))await action(()=>cloud.setEventClosed(closing))();};$('deleteEventBtn').onclick=async()=>{if(confirm('Xóa sự kiện này cùng toàn bộ dữ liệu? Thao tác không thể hoàn tác.'))await action(()=>cloud.deleteCurrentEvent())();};
$('adminRole').onchange=render;$('addAdminBtn').onclick=action(async()=>{await cloud.addAdmin($('adminEmail').value,$('adminName').value,$('adminRole').value,$('adminCanManage').checked);$('adminEmail').value='';$('adminName').value='';$('adminCanManage').checked=false;});$('adminRows').onclick=async e=>{const b=e.target.closest('[data-remove-admin]');if(b&&confirm('Xóa quyền admin của '+b.dataset.removeAdmin+'?'))await action(()=>cloud.removeAdmin(b.dataset.removeAdmin))();};
$('rows').onclick=async e=>{const image=e.target.closest('[data-view-photo]'),del=e.target.closest('[data-delete-scan]');if(image){const p=cloud.photos.find(x=>x.id===image.dataset.viewPhoto);if(p)viewImage(p.imageData);}if(del&&confirm('Xóa lượt quét MSSV '+del.dataset.deleteScan+'?'))await action(()=>cloud.deleteAttendance(del.dataset.deleteScan))();};
$('photoRows').onclick=async e=>{const view=e.target.closest('[data-view-photo]'),save=e.target.closest('[data-photo-save]'),del=e.target.closest('[data-photo-delete]');if(view){const p=cloud.photos.find(x=>x.id===view.dataset.viewPhoto);if(p)viewImage(p.imageData);}if(save){const input=document.querySelector(`[data-photo-input="${save.dataset.photoSave}"]`);await action(()=>cloud.resolvePhoto(save.dataset.photoSave,input.value))();}if(del&&confirm('Xóa hình chụp này?'))await action(()=>cloud.deletePhoto(del.dataset.photoDelete))();};
function viewImage(src){viewerScale=1;$('viewerImage').src=src;applyZoom();$('imageViewerDialog').showModal();}function applyZoom(){viewerScale=Math.max(.5,Math.min(4,viewerScale));$('viewerImage').style.width=(viewerScale*100)+'%';$('zoomReset').textContent=Math.round(viewerScale*100)+'%';}$('closeImageViewer').onclick=()=>$('imageViewerDialog').close();$('zoomIn').onclick=()=>{viewerScale+=.25;applyZoom();};$('zoomOut').onclick=()=>{viewerScale-=.25;applyZoom();};$('zoomReset').onclick=()=>{viewerScale=1;applyZoom();};
function normalizeHeader(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function parseRoster(data){const wb=XLSX.read(data,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,raw:false,defval:''});let header=-1,mi=-1,ni=-1;for(let i=0;i<Math.min(rows.length,15);i++){const h=rows[i].map(normalizeHeader);mi=h.findIndex(x=>['mssv','masosinhvien','studentid','masv'].includes(x));ni=h.findIndex(x=>['hoten','hovaten','tensinhvien','fullname','name'].includes(x));if(mi>=0&&ni>=0){header=i;break;}}if(header<0)throw Error('Không tìm thấy hai cột MSSV và Họ tên trong 15 dòng đầu.');return rows.slice(header+1).map(r=>({mssv:String(r[mi]||'').trim().toUpperCase(),name:String(r[ni]||'').trim()})).filter(r=>/^(?=.{8,12}$)(?=.*\d)[A-Z0-9]+$/.test(r.mssv)&&r.name);}
$('rosterFile').onchange=async()=>{const file=$('rosterFile').files[0];if(!file)return;await action(async()=>{const rows=parseRoster(await file.arrayBuffer());if(!confirm(`Tìm thấy ${rows.length} sinh viên. Thay danh sách đăng ký hiện tại?`))return;await cloud.replaceRoster(rows);})();$('rosterFile').value='';};
function exportRows(){return [...cloud.rows].sort((a,b)=>a.mssv.localeCompare(b.mssv,undefined,{numeric:true})).map((r,i)=>({STT:i+1,MSSV:r.mssv,'Sự kiện':r.eventName||cloud.eventName,'Thành viên quét':r.memberName||'Không rõ','Thời gian':time(r.time)}));}
function filename(ext){return safe(cloud.eventName)+'_'+cloud.day+'.'+ext;}$('excelBtn').onclick=()=>{const ws=XLSX.utils.json_to_sheet(exportRows()),wb=XLSX.utils.book_new();ws['!cols']=[{wch:7},{wch:18},{wch:35},{wch:30},{wch:22}];XLSX.utils.book_append_sheet(wb,ws,'Diem danh');XLSX.writeFile(wb,filename('xlsx'));};$('csvBtn').onclick=()=>{const blob=new Blob(['\ufeff'+XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(exportRows()))],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename('csv');a.click();URL.revokeObjectURL(a.href);};$('jsonBtn').onclick=()=>{const blob=new Blob([JSON.stringify({day:cloud.day,eventId:cloud.eventId,eventName:cloud.eventName,members:cloud.members,roster:cloud.roster,attendance:cloud.rows,photos:cloud.photos},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename('json');a.click();URL.revokeObjectURL(a.href);};$('deleteAllBtn').onclick=async()=>{if(confirm('Xóa toàn bộ lượt điểm danh của sự kiện đang chọn? Hãy xuất Excel trước.'))await action(()=>cloud.clearVisible())();};

$('day').value=vietnamDay();await cloud.prepare(DEFAULT_FIREBASE_CONFIG);if(cloud.settings)await cloud.restore();render();
